version: '3.7'
services:  

#   elasticsearch6:
#     build:
#       context: .
#       dockerfile: elasticsearch6/Dockerfile
#     image: elasticsearch6-image:v1
#     container_name: elasticsearch-zipkin
#     ports:
#       - 9200:9200
#     restart: always
#     networks:
#       - zipkin-network
#     volumes:
#       - elasticsearch-data:/usr/share/elasticsearch/data
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "100m"
#         max-file: "3"
#     deploy:
#       resources:
#         limits:
#           cpus: '0.50'
#           memory: 1500M

  cassandra-service:
    build:
      context: .
      dockerfile: cassandra/Dockerfile
    image: zipkin-cassandra:v1
    container_name: zipkin-cassandra-server
    ports:
      - "9042:9042"
    restart: always
    networks:
      - zipkin-network
    volumes:
    #   - cassandra-data:/var/lib/cassandra
      - cassandra-data:/cassandra/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          # for development or testing: 4 cpu min server host, for production: 8 cpu min server host
          cpus: '0.50'
          # for development or testing min value: 2048M (2G), for production min value: 4096M (4G), recomended value: 8192M (8G)
          memory: 2560M

  rabbitmq-service:
    image: rabbitmq:3.8.3-rc.2-management-alpine
    container_name: zipkin-rabbitmq-server
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - zipkin-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 250M

#   kafka-service:
#     image: openzipkin/zipkin-kafka
#     container_name: zipkin-kafka-server
#     ports:
#       - 2181:2181
#       - 9092:9092
#       - 19092:19092
#     restart: always
#     networks:
#       - zipkin-network
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "100m"
#         max-file: "3"
#     deploy:
#       resources:
#         limits:
#           cpus: '0.50'
#           memory: 250M

  zipkin-service:
    build:
      context: .
      dockerfile: zipkin/Dockerfile
    image: zipkin-web:v1
    container_name: zipkin-web-server
    ports:
      - "9411:9411"
    restart: always
    networks:
      - zipkin-network
    depends_on: 
      - cassandra-service
      - rabbitmq-service
    #   - kafka-service
    environment:
      RABBIT_ADDRESSES: zipkin-rabbitmq-server:5672
      # for development or testing: 2, for production: 4
      RABBIT_CONCURRENCY: 2
      #KAFKA_BOOTSTRAP_SERVERS: zipkin-kafka-server:9092
      STORAGE_TYPE: cassandra3
      # When using the test docker image, or have schema pre-installed, you don't need to re-install it
      CASSANDRA_ENSURE_SCHEMA: 'false'
      # When overriding this value, note the minimum supported version is 3.9
      # If you you cannot run 3.9+, but can run 2.2+, set STORAGE_TYPE=cassandra
      CASSANDRA_CONTACT_POINTS: zipkin-cassandra-server:9042
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 350M

#   curator:
#     # image: anjia0532/docker-curator:5.5.3
#     build:
#       context: .
#       dockerfile: curator/Dockerfile
#       args:
#         - CURATOR_VERSION=5.8.1
#     image: curator-image:v1
#     container_name: curator-zipkin
#     environment:
#       UNIT_COUNT: 1 # 10
#       UNIT: days # seconds minutes hours days weeks months years
#       ES_HOST: elasticsearch-zipkin
#     networks:
#       - zipkin-network
#     depends_on:
#       - elasticsearch6
#     deploy:
#       resources:
#         limits:
#           cpus: '0.25'
#           memory: 30M
          
networks:
  zipkin-network:

volumes:
  rabbitmq-data:
#   elasticsearch-data:
  cassandra-data:
